### ISSUE TITLE
No permite calcular la nota sin llenar todos los campos

### ISSUE THREAD

**Issue by wgcotera** [aloussase/polipromedios#1]
- Hay casos donde las materias no tienen componente práctico y no es necesario llenar la información correspondiente a el.
- Un escenario donde el usuario quiera calcular el resultado unicamente usando sus notas del primer y segundo parcial.

**Comment by wgcotera** [comment]
Entiendo, pero seria mas amigable para el usuario evitar que llene campos que no necesita para calcular su nota.

**Comment by aloussase** [comment]
Puedes abrir una PR implementando el cambio :)
